services:
  # Backend Django API
  - type: web
    name: django-api
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "cd django-back && gunicorn primerApp.wsgi:application"
    plan: free
    healthCheckPath: /api/
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
    scaling:
      minInstances: 1
      maxInstances: 1

  # Frontend React
  - type: web
    name: react-frontend
    env: node
    region: oregon
    buildCommand: "cd react-client && npm install && npm run build && cp build/index.html build/404.html"
    staticPublishPath: ./react-client/build
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
